# Adoptable Pet Bot

service: adoptable-pet-bot
frameworkVersion: ">=1.8.0"

provider:
  name: aws
  runtime: nodejs4.3
  region: us-east-1

# service wide environment variables
  environment:
    TWIT_API_KEY: ${file(./env.json):TWIT_API_KEY}
    TWIT_API_KEY_SECRET: ${file(./env.json):TWIT_API_KEY_SECRET}
    TWIT_ACCESS_TOKEN: ${file(./env.json):TWIT_ACCESS_TOKEN}
    TWIT_ACCESS_TOKEN_SECRET: ${file(./env.json):TWIT_ACCESS_TOKEN_SECRET}
    TWIT_TIMEOUT_MS: ${file(./env.json):TWIT_TIMEOUT_MS}
    SHELTER_ID: ${file(./env.json):SHELTER_ID}
    ADOPT_API_KEY: ${file(./env.json):ADOPT_API_KEY}
    SHELTER_NAME: ${file(./env.json):SHELTER_NAME}

functions:
  tweetPet:
    handler: handlers/tweetPet.tweetPet
    description: Tweets Adoptable Pets on a Schedule
    memorySize: 512 
    timeout: 10
    events:
      - schedule: rate(6 hours)
